const menuconfig=[
    {
        title:'电影',
        key:'/movie',
        childern:[
            {
                title:'动作',
                key:'/pay/jilu'
            },
            {
                title:'喜剧',
                key:'/pay/liushui'
            },
            {
                title:'爱情',
                key:'/pay/mingxi'
            },
            {
                title:'文艺',
                key:'/pay/lianlu'
            }
        ]
    },
    {
        title:'明星',
        key:'/star',
        childern:[
            {
                title:'港台',
                key:'/star/gangtai'
            },
            {
                title:'大陆',
                key:'/star/dalu'
            }
        ]
    },
    {
        title:'结算',
        key:'/jiesuan',
        childern:[
            {
                title:'商户结算',
                key:'/jiesuan/shanghu'
            },
            {
                title:'打款暂停',
                key:'/jiesuan/zanting'
            },
            {
                title:'打款恢复',
                key:'/jiesuan/huifu'
            }
        ]
    }
]

export default menuconfig;